baseURL = "https://jaskirat1208.github.io/"
title = "ACA"
author = "Jaskirat Singh"
paginate = 3
theme = "BluestNight"
contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"
canonifyurls = true

enableRobotsTXT = true # Suggested, enable robots.txt file

[outputs]
    home = ["HTML", "CSS", "JSON", "RSS"]

[Params]
    tagline = "Association of Computing Activities"
    description = "Association of Computing activities" # Description of your site
    authorbox = true
    author = "ACA"
    post_navigation = true
    alert = "NO RECENT NOTIFICATIONS"

[Params.widgets]
    search = false
    recent_articles = true
    categories = true
    tags = true
    tags_counter = false

[menu]
    [[menu.main]]
        name = "Home"
        weight = 2
        url = "/"
    [[menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects"

[Params.social]
    facebook = "aca.cse.iitk"
